
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nloyvkejuxdhbjjmxpxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sb3l2a2VqdXhkaGJqam14cHhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MjMxNjAsImV4cCI6MjA1OTQ5OTE2MH0.oE8UHL38Bgp3IoNqjf_oBsPPkvsoJdaK8_nSqOcQo58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
